main: me.featureable.staffassistant.StaffAssistant
name: StaffAssistant
version: 1.0.0
author: Featureable
description: The better way to moderate your server.
website: www.featureable.cf

commands:
  clearchat:
    aliases: [cc]
    description: Clear the chat.
  staffchat:
    aliases: [sc]
    description: Enable/Disable staff chat.
  togglechat:
    aliases: [tc, chat]
    description: Enable/Disable chat.

permissions:
  sa.bypass:
    description: Bypass disabled chat.
    default: op
  sa.staffchat:
    description: Allows a player to see and message staffchat.
    default: op
  sa.togglechat:
    description: Toggle chat.
    default: op