main: me.featureable.staffassistant.StaffAssistant
name: StaffAssistant
version: 1.0.1
author: Featureable
description: Enhance staffing on your server.
website: www.featureable.cf

commands:
  clearchat:
    aliases: [cc]
    description: Clear the chat.
  staffchat:
    aliases: [sc]
    description: Enable/Disable staff chat.
  togglechat:
    aliases: [tc, chat]
    description: Enable/Disable chat.

permissions:
  sa.bypass:
    description: Allows a player to bypass disabled chat.
    default: op
  sa.staffchat:
    description: Allows a player to see and chat in staffchat.
    default: op
  sa.togglechat:
    description: Allows a player to toggle chat.
    default: op